# ----------------------------------------------------------
#  - alias: outside_carport
#    initial_state: True
#    hide_entity: False
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev60_motion
#        to: 'on'
#    action:
#      service: light.turn_on
#      entity_id: light.dev60
# ----------------------------------------------------------      
# ------------------- outside_carport ----------------------
  - alias: outside_carport
    initial_state: True
    hide_entity: False
    trigger: 
      - platform: state
        entity_id: binary_sensor.dev03_motion
        to: 'off'
 #       for: 
 #         hours: 0
 #         minutes: 2
 #         seconds: 0
      - platform: state
        entity_id: binary_sensor.dev03_motion
        to: 'on'
    action:
      - service_template: >
          {% if is_state('binary_sensor.dev03_motion','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev03
# ------------------- entrance Room ------------------------