################################################# to be deleted
# -------------- templates ----------------------
# -------------- all motion sensors -------------
#  - platform: template
#    sensors:
#      g_motion:
#        device_class: motion
#        value_template: >-
#          {%- if is_state("binary_sensor.dev03_motion", "on")
#             or is_state("binary_sensor.dev61_motion", "on")  
#          -%}     
#          true
#          {%- else -%}
#          false
#          {%- endif %}
#        entity_id:
#          - binary_sensor.dev03_motion
#          - binary_sensor.dev61_motion
#          - binary_sensor.dev62_motion
#          - binary_sensor.dev63_motion
#          - binary_sensor.dev71_motion
#          - binary_sensor.dev72_motion
#          - binary_sensor.dev73_motion
#          - binary_sensor.dev75_motion
#
################################################# to be deleted
# -------------- all motion sensors -------------
  - platform: mqtt
    state_topic: "std/dev03/s/pir/status"
    name: "dev03_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev05/s/pir/status"
    name: "dev05_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev62/s/pir/status"
    name: "dev62_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev61/s/pir/status"
    name: "dev61_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev63/s/pir/status"
    name: "dev63_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev70/s/pir/status"
    name: "dev70_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev71/s/pir/status"
    name: "dev71_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev72/s/pir/status"
    name: "dev72_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev73/s/pir/status"
    name: "dev73_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev75/s/pir/status"
    name: "dev75_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev101/s/0/pir/state"
    name: "dev101_motion"
    device_class: motion
  - platform: mqtt
    state_topic: "std/dev102/s/0/pir/state"
    name: "dev102_motion"
    device_class: motion
#------------------------------------------------