  - platform: time_date
    display_options:
      - 'time'
# -----------------------------------------------------------
# --------------- MQTT --------------------------------------
  - platform: mqtt
    state_topic: "dev20/#"
    name: "dev20"

  - platform: mqtt
    state_topic: "std/dev20/s/temp_hum/temp"
    name: "dev20_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev20/s/temp_hum/hum"
    name: "dev20_humidity_dht"
    unit_of_measurement: "%"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev21/#"
    name: "dev21"

  - platform: mqtt
    state_topic: "std/dev21/s/temp_hum/temp"
    name: "dev21_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev21/s/temp_hum/hum"
    name: "dev21_humidity_dht"
    unit_of_measurement: "%"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev22/#"
    name: "dev22"

  - platform: mqtt
    state_topic: "std/dev22/s/temp_hum/temp"
    name: "dev22_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev22/s/temp_hum/hum"
    name: "dev22_humidity_dht"
    unit_of_measurement: "%"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev23/#"
    name: "dev23"

  - platform: mqtt
    state_topic: "std/dev23/s/temp_hum/temp"
    name: "dev23_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev23/s/temp_hum/hum"
    name: "dev23_humidity_dht"
    unit_of_measurement: "%"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev24/#"
    name: "dev24"

  - platform: mqtt
    state_topic: "std/dev24/s/temp_hum/temp"
    name: "dev24_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev24/s/temp_hum/hum"
    name: "dev24_humidity_dht"
    unit_of_measurement: "%"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev25/#"
    name: "dev25"

  - platform: mqtt
    state_topic: "std/dev25/s/temp_hum/temp"
    name: "dev25_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev25/s/temp_hum/hum"
    name: "dev25_humidity_dht"
    unit_of_measurement: "%"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev27/#"
    name: "dev27"

  - platform: mqtt
    state_topic: "std/dev27/s/temp_hum/temp"
    name: "dev27_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev27/s/temp_hum/hum"
    name: "dev27_humidity_dht"
    unit_of_measurement: "%"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev28/#"
    name: "dev28"

  - platform: mqtt
    state_topic: "std/dev28/s/temp_hum/temp"
    name: "dev28_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev28/s/temp_hum/hum"
    name: "dev28_humidity_dht"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev28/s/temp_hum/temp1"
    name: "dev28_temperature_dht1"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev28/s/temp_hum/hum1"
    name: "dev28_humidity_dht1"
    unit_of_measurement: "%"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev30/#"
    name: "dev30"

  - platform: mqtt
    state_topic: "std/dev30/s/bme/temp"
    name: "dev30_temperature_bme"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev30/s/bme/hum"
    name: "dev30_humidity_bme"
    unit_of_measurement: "%"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev70/#"
    name: "dev70"

  - platform: mqtt
    state_topic: "std/dev70/s/temp_hum/temp"
    name: "dev70_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev70/s/temp_hum/hum"
    name: "dev70_humidity_dht"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev70/s/temt6000/raw"
    name: "dev70_brightness_temt6000"
    unit_of_measurement: "raw"
  
  - platform: mqtt
    state_topic: "std/dev70/s/health/tic"
    name: "dev70_health_tic"
    unit_of_measurement: "cnt"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev71/#"
    name: "dev71"

  - platform: mqtt
    state_topic: "std/dev71/s/temp_hum/temp"
    name: "dev71_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev71/s/temp_hum/hum"
    name: "dev71_humidity_dht"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev71/s/temt6000/raw"
    name: "dev71_brightness_temt6000"
    unit_of_measurement: "raw"
  
  - platform: mqtt
    state_topic: "std/dev71/s/health/tic"
    name: "dev71_health_tic"
    unit_of_measurement: "cnt"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev72/#"
    name: "dev72"

  - platform: mqtt
    state_topic: "std/dev72/s/temp_hum/temp"
    name: "dev72_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev72/s/temp_hum/hum"
    name: "dev72_humidity_dht"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev72/s/temt6000/raw"
    name: "dev72_brightness_temt6000"
    unit_of_measurement: "raw"
  
  - platform: mqtt
    state_topic: "std/dev72/s/health/tic"
    name: "dev72_health_tic"
    unit_of_measurement: "cnt"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev73/#"
    name: "dev73"

  - platform: mqtt
    state_topic: "std/dev73/s/temp_hum/temp"
    name: "dev73_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev73/s/temp_hum/hum"
    name: "dev73_humidity_dht"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev73/s/temt6000/raw"
    name: "dev73_brightness_temt6000"
    unit_of_measurement: "raw"
  
  - platform: mqtt
    state_topic: "std/dev73/s/health/tic"
    name: "dev73_health_tic"
    unit_of_measurement: "cnt"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev75/#"
    name: "dev75"

  - platform: mqtt
    state_topic: "std/dev75/s/temp_hum/temp"
    name: "dev75_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev75/s/temp_hum/hum"
    name: "dev75_humidity_dht"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev75/s/temt6000/raw"
    name: "dev75_brightness_temt6000"
    unit_of_measurement: "raw"

  - platform: mqtt
    state_topic: "std/dev75/s/health/tic"
    name: "dev75_health_tic"
    unit_of_measurement: "cnt"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev101/#"
    name: "dev101"

  - platform: mqtt
    state_topic: "std/dev101/s/0/dht/temp"
    name: "dev101_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev101/s/0/dht/hum"
    name: "dev101_humidity_dht"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev101/s/0/temt6x/raw"
    name: "dev101_brightness_temt6x"
    unit_of_measurement: "raw"

  - platform: mqtt
    state_topic: "std/dev101/s/health/tic"
    name: "dev101_health_tic"
    unit_of_measurement: "cnt"

  - platform: mqtt
    state_topic: "std/dev101/s/0/mija/temp"
    name: "dev101_temperature_mija0"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev101/s/0/mija/hum"
    name: "dev101_humidity_mija0"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev101/s/0/mija/batt"
    name: "dev101_battery_mija0"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev101/s/0/mija/cnt"
    name: "dev101_healthtic_mija0"
    unit_of_measurement: "cnt"

  - platform: mqtt
    state_topic: "std/dev101/s/1/mija/temp"
    name: "dev101_temperature_mija1"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev101/s/1/mija/hum"
    name: "dev101_humidity_mija1"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev101/s/1/mija/batt"
    name: "dev101_battery_mija1"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev101/s/1/mija/cnt"
    name: "dev101_healthtic_mija1"
    unit_of_measurement: "cnt"

  - platform: mqtt
    state_topic: "std/dev101/s/2/mija/temp"
    name: "dev101_temperature_mija2"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev101/s/2/mija/hum"
    name: "dev101_humidity_mija2"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev101/s/2/mija/batt"
    name: "dev101_battery_mija2"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev101/s/2/mija/cnt"
    name: "dev101_healthtic_mija2"
    unit_of_measurement: "cnt"

  - platform: mqtt
    state_topic: "std/dev101/s/3/mija/temp"
    name: "dev101_temperature_mija3"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev101/s/3/mija/hum"
    name: "dev101_humidity_mija3"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev101/s/3/mija/batt"
    name: "dev101_battery_mija3"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev101/s/3/mija/cnt"
    name: "dev101_healthtic_mija3"
    unit_of_measurement: "cnt"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev102/#"
    name: "dev102"

  - platform: mqtt
    state_topic: "std/dev102/s/0/dht/temp"
    name: "dev102_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev102/s/0/dht/hum"
    name: "dev102_humidity_dht"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev102/s/0/temt6x/raw"
    name: "dev102_brightness_temt6x"
    unit_of_measurement: "raw"

  - platform: mqtt
    state_topic: "std/dev102/s/health/tic"
    name: "dev102_health_tic"
    unit_of_measurement: "cnt"

  - platform: mqtt
    state_topic: "std/dev102/s/0/mija/temp"
    name: "dev102_temperature_mija0"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev102/s/0/mija/hum"
    name: "dev102_humidity_mija0"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev102/s/0/mija/batt"
    name: "dev102_battery_mija0"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev102/s/0/mija/cnt"
    name: "dev102_healthtic_mija0"
    unit_of_measurement: "cnt"

  - platform: mqtt
    state_topic: "std/dev102/s/1/mija/temp"
    name: "dev102_temperature_mija1"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev102/s/1/mija/hum"
    name: "dev102_humidity_mija1"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev102/s/1/mija/batt"
    name: "dev102_battery_mija1"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev102/s/1/mija/cnt"
    name: "dev102_healthtic_mija1"
    unit_of_measurement: "cnt"

  - platform: mqtt
    state_topic: "std/dev102/s/2/mija/temp"
    name: "dev102_temperature_mija2"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev102/s/2/mija/hum"
    name: "dev102_humidity_mija2"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev102/s/2/mija/batt"
    name: "dev102_battery_mija2"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev102/s/2/mija/cnt"
    name: "dev102_healthtic_mija2"
    unit_of_measurement: "cnt"

  - platform: mqtt
    state_topic: "std/dev102/s/3/mija/temp"
    name: "dev102_temperature_mija3"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev102/s/3/mija/hum"
    name: "dev102_humidity_mija3"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev102/s/3/mija/batt"
    name: "dev102_battery_mija3"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "std/dev102/s/3/mija/cnt"
    name: "dev102_healthtic_mija3"
    unit_of_measurement: "cnt"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev200/#"
    name: "dev200"

  - platform: mqtt
    state_topic: "std/dev200/s/rki/ce/c7"
    name: "dev200_rki_celle_7day"
    unit_of_measurement: "cnt"

  - platform: mqtt
    state_topic: "std/dev200/s/rki/noh/c7"
    name: "dev200_rki_noh_7day"
    unit_of_measurement: "cnt"
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev11/#"
    name: "dev11"

  - platform: mqtt
    state_topic: "std/dev11/s/temp_hum/temp"
    name: "dev11_temperature_dht"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev11/s/temp_hum/hum"
    name: "dev11_humidity_dht"
    unit_of_measurement: "%"
  
  - platform: mqtt
    state_topic: "std/dev11/s/temp_hum/temp1"
    name: "dev11_temperature_dht1"
    unit_of_measurement: "ºC"

  - platform: mqtt
    state_topic: "std/dev11/s/temp_hum/hum1"
    name: "dev11_humidity_dht1"
    unit_of_measurement: "%"
# -----------------------------------------------------------
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use
      - type: last_boot
# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev300/#"
    name: "dev300"

  - platform: mqtt
    state_topic: "std/dev300/s/hb/heart_beat"
    name: "dev300_heart_beat"
    unit_of_measurement: "cnt"

  - platform: mqtt
    state_topic: "std/dev300/s/hb/time_now"
    name: "dev300_time_now"

  - platform: mqtt
    state_topic: "std/dev300/s/hb/ts_now"
    name: "dev300_ts_now"

# -----------------------------------------------------------
  - platform: mqtt
    state_topic: "dev301/#"
    name: "dev301"

  - platform: mqtt
    state_topic: "std/dev301/s/ener_wat/gas"
    name: "dev301_gas"
    unit_of_measurement: "qm"

  - platform: mqtt
    state_topic: "std/dev301/s/ener_wat/power"
    name: "dev301_power"
    unit_of_measurement: "kWh"

  - platform: mqtt
    state_topic: "std/dev301/s/ener_wat/water"
    name: "dev301_water"
    unit_of_measurement: "qm"

  - platform: mqtt
    state_topic: "std/dev301/s/ener_wat/date"
    name: "dev301_date"
