# ----------------------------------------------------------
#  - alias: outside_carport
#    initial_state: True
#    hide_entity: False
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev60_motion
#        to: 'on'
#    action:
#      service: light.turn_on
#      entity_id: light.dev60
# ----------------------------------------------------------      
# ------------------- outside_carport ----------------------
#  - alias: outside_carport
#    initial_state: True
#    hide_entity: False
#    trigger: 
#      - platform: state
#        entity_id: binary_sensor.dev03_motion
#        to: 'off'
#        for: 
#          hours: 0
#          minutes: 1
#          seconds: 0
#      - platform: state
#        entity_id: binary_sensor.dev03_motion
#        to: 'on'
#    action:
#      - service_template: >
#          {% if is_state('binary_sensor.dev03_motion','on') %}
#            light.turn_on
#          {% else %}
#            light.turn_off
#          {% endif %}
#        entity_id: 
#          - light.dev03
# ------------------- alternative carport light control ------
#  - alias: Outside Light Control ON
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev03_motion
#        to: 'on'
#    condition:
#      condition: and
#      conditions:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#      - condition: state
#        entity_id: light.dev03
#        state: 'off'
#    action:
#      - service: light.turn_on
#        entity_id: light.dev03

#  - alias: Outside Light Control OFF
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev03_motion
#        to: 'off'
#        for:
#          minutes: 01
#          seconds: 00
#    action:
#      - service: light.turn_off
#        entity_id: light.dev03
# ---------------------------------------------------------- 
# ------------------- Carport 2 light control --------------
#  - alias: Carport Out Light ON
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev62_motion
#        to: 'on'
#    condition:
#      condition: and
#      conditions:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#      - condition: state
#        entity_id: light.dev62
#        state: 'off'
#    action:
#      - service: light.turn_on
#        entity_id: light.dev62

#  - alias: Carport Out Light OFF
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev62_motion
#        to: 'off'
#        for:
#          minutes: 01
#          seconds: 00
#    action:
#      - service: light.turn_off
#        entity_id: light.dev62
# ----------------------------------------------------------
# ------------------- hall light control -------------------
#  - alias: Hall ground floor Orient Light ON
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev70_motion
#        to: 'on'
#    condition:
#      condition: and
#      conditions:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#      - condition: state
#        entity_id: light.dev70
#        state: 'off'
#    action:
#      - service: light.turn_on
#        entity_id: light.dev70

#  - alias: Hall ground floor Orient Light OFF
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev70_motion
#        to: 'off'
#        for:
#          minutes: 01
#          seconds: 00
#    action:
#      - service: light.turn_off
#        entity_id: light.dev70
# ----------------------------------------------------------
# ------------------- carport light control ----------------
#  - alias: Carport Inside Orient Light ON
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev71_motion
#        to: 'on'
#    condition:
#      condition: and
#      conditions:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#      - condition: state
#        entity_id: light.dev71
#        state: 'off'
#    action:
#      - service: light.turn_on
#        entity_id: light.dev71

#  - alias: Carport Inside Orient Light OFF
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev71_motion
#        to: 'off'
#        for:
#          minutes: 01
#          seconds: 00

#    action:
#      - service: light.turn_off
#        entity_id: light.dev71
# ---------------------------------------------------------- 
# ------------------- living room light control ------------
#  - alias: Living Room Orient Light ON
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev72_motion
#        to: 'on'
#    condition:
#      condition: and
#      conditions:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#      - condition: state
#        entity_id: light.dev72
#        state: 'off'
#    action:
#      - service: light.turn_on
#        entity_id: light.dev72

#  - alias: Living Room Orient Light OFF
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev72_motion
#        to: 'off'
#        for:
#          minutes: 01
#          seconds: 00
#    action:
#      - service: light.turn_off
#        entity_id: light.dev72
# ---------------------------------------------------------- 
# ------------------- hall light 2 control -----------------
#  - alias: Hall first floor Orient Light ON
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev73_motion
#        to: 'on'
#    condition:
#      condition: and
#      conditions:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#      - condition: state
#        entity_id: light.dev73
#        state: 'off'
#    action:
#      - service: light.turn_on
#        entity_id: light.dev73

#  - alias: Hall first floor Orient Light OFF
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev73_motion
#        to: 'off'
#        for:
#          minutes: 01
#          seconds: 00
#    action:
#      - service: light.turn_off
#        entity_id: light.dev73
# ----------------------------------------------------------
# ------------------- hall light 2 control -----------------
#  - alias: Hall first floor 2 Orient Light ON
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev75_motion
#        to: 'on'
#    condition:
#      condition: and
#      conditions:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#      - condition: state
#        entity_id: light.dev75
#        state: 'off'
#    action:
#      - service: light.turn_on
#        entity_id: light.dev75
#  - alias: Hall first floor 2 Orient Light OFF
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev75_motion
#        to: 'off'
#        for:
#          minutes: 01
#          seconds: 00
#    action:
#      - service: light.turn_off
#        entity_id: light.dev75
# ----------------------------------------------------------

# ------------------- ESP32 control ------------------------
#  - alias: ESP32 Orient Light ON
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev101_motion
#        to: 'on'
#    condition:
#      condition: and
#      conditions:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#      - condition: state
#        entity_id: light.dev101
#        state: 'off'
#    action:
#      - service: light.turn_on
#        entity_id: light.dev101

#  - alias: ESP32 Orient Light OFF
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev101_motion
#        to: 'off'
#        for:
#          minutes: 01
#          seconds: 00
#    action:
#      - service: light.turn_off
#        entity_id: light.dev101
# ----------------------------------------------------------

# ------------------- garden house light control -----------
#  - alias: Garden House Orient Light ON
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev63_motion
#        to: 'on'
#    condition:
#      condition: and
#      conditions:
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#      - condition: state
#        entity_id: light.dev63
#        state: 'off'
#    action:
#      - service: light.turn_on
#        entity_id: light.dev63

#  - alias: Carport Inside Orient Light OFF
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.dev63_motion
#        to: 'off'
#        for:
#          minutes: 01
#          seconds: 00
#    action:
#      - service: light.turn_off
#        entity_id: light.dev63
# ----------------------------------------------------------