homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.673469
  longitude: 10.086624
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 58.76
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

weather:
  - platform: darksky
    api_key: !secret darksky_key

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Enable the database storage
recorder:
  db_url: mysql://hass:ssah@core-mariadb/homeassistant

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
#sensor:
#  - platform: yr

octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_api

# Text to speech
tts:
  - platform: google_translate

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mq_user
  password: !secret mq_pass

sensor: !include sensors.yaml
#switch: !include switches.yaml
group: !include groups.yaml
light: !include lights.yaml
#device_tracker: !include tracker.yaml
binary_sensor: !include b_sensors.yaml
#input_slider: !include slider.yaml
automation: !include automations.yaml
script: !include scripts.yaml
camera: !include cameras.yaml
