title: Home
views:
  - badges: []
    cards:
      - entity: weather.dark_sky
        name: Wetter Trend
        type: weather-forecast
      - aspect_ratio: 80%
        title: Regenradar
        type: iframe
        url: >-
          https://embed.windy.com/embed2.html?lat=51.645&lon=8.921&zoom=5&level=surface&overlay=rain&menu=&message=&marker=true&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=52.617&detailLon=10.083&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1
      - entities:
          - entity: sensor.dev72_temperature_dht
          - entity: sensor.dev72_humidity_dht
          - entity: sensor.dev72_brightness_temt6000
          - entity: binary_sensor.dev72_motion
          - entity: light.dev72
          - entity: light.dev80_l1
          - entity: light.dev80_l2
          - entity: light.dev80_l3
          - entity: light.dev04
        show_header_toggle: false
        title: Wohnzimmer
        type: entities
      - entities:
          - entity: sensor.dev101_temperature_dht
          - entity: sensor.dev101_humidity_dht
          - entity: sensor.dev101_brightness_temt6x
          - entity: binary_sensor.dev101_motion
          - entity: light.dev101
          - entity: light.dev101_r1
        show_header_toggle: false
        title: Flur unten
        type: entities
      - entities:
          - sensor.dev23_temperature_dht
          - sensor.dev23_humidity_dht
        show_header_toggle: false
        title: Dachboden
        type: entities
      - entities:
          - entity: sensor.dev71_temperature_dht
          - entity: sensor.dev71_humidity_dht
          - entity: sensor.dev71_brightness_temt6000
          - entity: light.dev71
          - entity: binary_sensor.dev71_motion
        show_header_toggle: false
        title: Werkstatt
        type: entities
        state_color: false
      - entities:
          - entity: sensor.dev102_temperature_dht
          - entity: sensor.dev102_humidity_dht
          - entity: sensor.dev102_brightness_temt6x
          - entity: binary_sensor.dev102_motion
          - entity: light.dev102
          - entity: light.dev102_r1
        show_header_toggle: false
        title: Flur oben
        type: entities
      - entities:
          - entity: sensor.dev28_temperature_dht
          - entity: sensor.dev28_humidity_dht
          - entity: sensor.dev28_temperature_dht1
          - entity: sensor.dev28_humidity_dht1
          - entity: light.dev50_r1
          - entity: light.dev50_r2
          - entity: light.dev50_r3
          - entity: light.dev50_r4
          - entity: light.dev50_r5
          - entity: light.dev50_r6
          - entity: light.dev50_r7
          - entity: light.dev50_r8
          - entity: light.dev01
        show_header_toggle: false
        title: Garten
        type: entities
      - type: entities
        entities:
          - entity: binary_sensor.dev05_motion
          - entity: light.dev05
          - entity: binary_sensor.dev62_motion
          - entity: light.dev62
        title: Carport
        show_header_toggle: false
      - entities:
          - entity: binary_sensor.dev63_motion
          - entity: light.dev63
        show_header_toggle: false
        title: Gartenhaus
        type: entities
      - entities:
          - entity: sensor.dev73_temperature_dht
          - entity: sensor.dev73_humidity_dht
          - entity: sensor.dev73_brightness_temt6000
          - entity: binary_sensor.dev73_motion
          - entity: light.dev73
        show_header_toggle: false
        title: Hauswirtschaftsraum
        type: entities
      - entities:
          - entity: sensor.dev101_temperature_mija1
          - entity: sensor.dev101_humidity_mija1
          - entity: sensor.dev101_battery_mija1
          - entity: sensor.dev101_healthtic_mija1
        show_header_toggle: false
        title: Badezimmer unten
        type: entities
      - entities:
          - entity: sensor.dev102_temperature_mija0
          - entity: sensor.dev102_humidity_mija0
          - entity: sensor.dev102_battery_mija0
          - entity: sensor.dev102_healthtic_mija0
        show_header_toggle: false
        title: Badezimmer oben
        type: entities
      - type: entities
        entities:
          - entity: sensor.dev102_temperature_mija2
          - entity: sensor.dev102_humidity_mija2
          - entity: sensor.dev102_battery_mija2
          - entity: sensor.dev102_healthtic_mija2
        title: Elternschlafzimmer
      - type: entities
        entities:
          - entity: sensor.dev102_temperature_mija3
          - entity: sensor.dev102_humidity_mija3
          - entity: sensor.dev102_battery_mija3
          - entity: sensor.dev102_healthtic_mija3
        title: Gästezimmer
      - type: history-graph
        entities:
          - entity: sensor.dev200_rki_celle_7day
          - entity: sensor.dev200_rki_noh_7day
        hours_to_show: 24
        refresh_interval: 0
        title: RKI 7 Tage Incident
      - type: entities
        entities:
          - entity: sensor.dev200_rki_celle_7day
            icon: 'mdi:hospital'
          - entity: sensor.dev200_rki_noh_7day
            icon: 'mdi:hospital'
        title: COVID-19 RKI Zahlen
    icon: 'mdi:home'
    path: default_view
    title: Home
  - badges: []
    cards:
      - entity: weather.dark_sky
        name: Vorhersage
        type: weather-forecast
      - aspect_ratio: 50%
        title: Radar
        type: iframe
        url: >-
          https://embed.windy.com/embed2.html?lat=51.645&lon=8.921&zoom=5&level=surface&overlay=rain&menu=&message=&marker=true&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=52.617&detailLon=10.083&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1
    icon: 'mdi:weather-sunny'
    path: wetter
    title: Wetter
  - badges: []
    cards:
      - detail: 0.1
        entity: sensor.dev23_temperature_dht
        hours_to_show: 48
        name: Dachboden
        theme: default
        type: sensor
        unit: °C
      - detail: 0.1
        entity: sensor.dev70_temperature_dht
        hours_to_show: 48
        name: Flur unten
        type: sensor
        unit: °C
      - detail: 0.1
        entity: sensor.dev71_temperature_dht
        hours_to_show: 48
        name: Carport Schuppen
        type: sensor
        unit: °C
      - detail: 0.1
        entity: sensor.dev72_temperature_dht
        hours_to_show: 48
        name: Wohnzimmer
        type: sensor
        unit: °C
      - detail: 0.1
        entity: sensor.dev73_temperature_dht
        hours_to_show: 48
        name: Flur oben
        type: sensor
        unit: °C
      - detail: 0.1
        entity: sensor.dev28_temperature_dht1
        hours_to_show: 48
        name: Garten Box innen
        type: sensor
        unit: °C
      - detail: 0.1
        entity: sensor.dev28_temperature_dht
        hours_to_show: 48
        name: Garten Box Außen
        type: sensor
        unit: °C
      - entity: sensor.dev21_temperature_dht
        name: Esszimmer
        type: sensor
        unit: °C
      - entities:
          - entity: sensor.dev73_temperature_dht
            name: Flur oben
          - entity: sensor.dev70_temperature_dht
            name: Flur unten
          - entity: sensor.dev72_temperature_dht
            name: Wohnzimmer
          - entity: sensor.dev21_temperature_dht
            name: Esszimmer
          - entity: sensor.dev23_temperature_dht
            name: Dachboden
          - entity: sensor.dev101_temperature_mija0
            name: Bad oben
          - entity: sensor.dev101_temperature_mija1
            name: Bad unten
        hours_to_show: 24
        refresh_interval: 0
        title: Innen- Temperaturen
        type: history-graph
      - entities:
          - entity: sensor.dev71_temperature_dht
            name: Carport Schuppen
          - entity: sensor.dev28_temperature_dht1
            name: Gartenbox innen
          - entity: sensor.dev28_temperature_dht
            name: Gartenbox außen
        title: Außen- Temperaturen
        type: history-graph
      - entity: sensor.dev101_temperature_mija0
        name: Badezimmer oben
        type: sensor
      - entity: sensor.dev101_temperature_mija1
        name: Badezimmer unten
        type: sensor
    icon: 'mdi:thermometer'
    path: groups_temperature
    title: Temperaturen
  - badges: []
    cards:
      - entities:
          - entity: sensor.dev73_humidity_dht
            name: Flur oben
          - entity: sensor.dev70_humidity_dht
            name: Flur unten
          - entity: sensor.dev72_humidity_dht
            name: Wohnzimmer
          - entity: sensor.dev21_humidity_dht
            name: Esszimmer
          - entity: sensor.dev23_humidity_dht
            name: Dachboden
        title: Innen- Luftfeuchte
        type: history-graph
      - entities:
          - entity: sensor.dev71_humidity_dht
            name: Carport Schuppen
          - entity: sensor.dev28_humidity_dht1
            name: Gartenbox innen
          - entity: sensor.dev28_humidity_dht
            name: Gartenbox außen
        title: Außen- Luftfeuchte
        type: history-graph
    icon: 'mdi:waves'
    path: groups_humid
    title: Humidity
  - icon: 'mdi:guy-fawkes-mask'
    path: system
    title: System
    badges: []
    cards:
      - entities:
          - entity: sensor.disk_use_percent
          - entity: sensor.memory_free
          - entity: sensor.processor_use_percent
          - entity: sensor.last_boot
        show_header_toggle: false
        title: System
        type: entities
      - entities:
          - entity: sensor.dev71_health_tic
          - entity: sensor.dev72_health_tic
          - entity: sensor.dev73_health_tic
          - entity: sensor.dev101_health_tic
          - entity: sensor.dev102_health_tic
        show_header_toggle: false
        title: Device Health Status
        type: entities
      - entities:
          - light.dev01
          - light.dev02
          - light.dev03
          - light.dev04
          - light.dev05
          - light.dev50_r1
          - light.dev50_r2
          - light.dev50_r3
          - light.dev50_r4
          - light.dev50_r5
          - light.dev50_r6
          - light.dev50_r7
          - light.dev50_r8
          - light.dev62
          - light.dev99
          - light.dev71
          - light.dev72
          - light.dev73
          - light.dev11_l1
          - light.dev11_l2
          - light.dev11_r1
          - light.dev11_r2
        show_header_toggle: false
        title: All lights
        type: entities
      - hold_action:
          action: none
        image: 'http://192.168.178.103/capture'
        tap_action:
          action: none
        type: picture
      - entities:
          - entity: binary_sensor.dev03_motion
          - entity: binary_sensor.dev62_motion
          - entity: binary_sensor.dev63_motion
          - entity: binary_sensor.dev71_motion
          - entity: binary_sensor.dev72_motion
          - entity: binary_sensor.dev73_motion
          - entity: binary_sensor.dev75_motion
          - entity: binary_sensor.dev101_motion
        title: Bewegungen
        type: entities
  - title: Test
    path: test
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.dev101_temperature_dht
          - entity: sensor.dev101_humidity_dht
          - entity: sensor.dev101_brightness_temt6x
          - entity: binary_sensor.dev101_motion
          - entity: light.dev101
          - entity: light.dev101_r1
        title: ESP32 Test
      - type: picture
        image: 'http://192.168.178.103:81/stream'
        tap_action:
          action: none
        hold_action:
          action: none
